MDScreen:
    name:"login"
    md_bg_color: 153/255, 255/255, 255/255,1
    MDGridLayout:
        cols:1
        size_hint: 0.90,0.90
        pos_hint: {"center_x":0.49,"center_y":0.60}
        Image:
            source: "Untitled16_20230523195024.png"

    MDGridLayout:
        cols:1
        size_hint: 0.85,0.85
        pos_hint: {"center_x":0.49,"center_y":0.43}
        Image:
            source: "Untitled18_20230523204533.png"