MDScreen:
    name:"edit_show_doc"
    BoxLayout:
        orientation: 'vertical'
        AsyncImage:
            id: my_image
            source: ''
    MDIconButton:
        icon : "arrow-left"
        pos_hint :{"center_x": 0.1, "center_y": 0.9}
        user_font_size: "30sp"
        theme_text_color: "Custom"
        text_color : rgba(26, 24, 58, 255)
        on_release:
            root.manager.current = 'Leave_Request_edit'

